const lectureData = {
    "2023": [
        { id: "10강_실무적용_기획서_작성하기_20230819", title: "10강 실무적용 기획서 작성하기", tag: "기획", img: "assets/lectures/10강_실무적용_기획서_작성하기_20230819/slide1.png", desc: "실무 기획서 작성 및 활용 교육" , totalSlides: 44 },
        { id: "10차시_자율주행_차량이_가져올_변화", title: "10차시 자율주행 차량이 가져올 변화", tag: "미래기술", img: "assets/lectures/10차시_자율주행_차량이_가져올_변화/slide1.png", desc: "모빌리티의 미래와 기술 트렌드" , totalSlides: 49 },
        { id: "11강_실무적용_기획서_작성하기_20230822", title: "11강 실무적용 기획서 작성하기", tag: "기획", img: "assets/lectures/11강_실무적용_기획서_작성하기_20230822/slide1.png", desc: "심화 기획 프로세스 분석" , totalSlides: 44 },
        { id: "11차시_스마트시티와_지속가능한_발전_-_복사본", title: "11차시 스마트시티와 지속가능 발전", tag: "스마트시티", img: "assets/lectures/11차시_스마트시티와_지속가능한_발전_-_복사본/slide1.png", desc: "도시 환경과 디지털 혁신" , totalSlides: 50 },
        { id: "12강_일잘러_뽑기_자기소개서_평가_면접_문항_생성_20230831", title: "12강 일잘러 뽑기 자기소개서 평가", tag: "인사", img: "assets/lectures/12강_일잘러_뽑기_자기소개서_평가_면접_문항_생성_20230831/slide1.png", desc: "AI 기반 채용 프로세스 이해" , totalSlides: 41 },
        { id: "12차시_기술윤리와_사회적_책임", title: "12차시 기술윤리와 사회적 책임", tag: "윤리", img: "assets/lectures/12차시_기술윤리와_사회적_책임/slide1.png", desc: "디지털 리더십과 윤리" , totalSlides: 58 },
        { id: "13강_GAI를_활용한_상담프로그램_활용_20230831", title: "13강 GAI 활용 상담 프로그램", tag: "복지", img: "assets/lectures/13강_GAI를_활용한_상담프로그램_활용_20230831/slide1.png", desc: "상담 실무를 위한 AI 도구" , totalSlides: 51 },
        { id: "13차시_교육의_미래와_온라인_학습", title: "13차시 교육의 미래와 온라인 학습", tag: "교육", img: "assets/lectures/13차시_교육의_미래와_온라인_학습/slide1.png", desc: "에듀테크와 학습자 중심 교육" , totalSlides: 50 },
        { id: "14강_비즈니스_컨설팅_GAI활용_20230831", title: "14강 비즈니스 컨설팅 GAI 활용", tag: "비즈니스", img: "assets/lectures/14강_비즈니스_컨설팅_GAI활용_20230831/slide1.png", desc: "AI를 활용한 기업 컨설팅" , totalSlides: 45 },
        { id: "14차시_에너지의_미래와_그린_기술", title: "14차시 에너지의 미래와 그린 기술", tag: "환경", img: "assets/lectures/14차시_에너지의_미래와_그린_기술/slide1.png", desc: "기후 위기 대응과 신기술" , totalSlides: 61 },
        { id: "15강_PDF문서뽀개기_20230831", title: "15강 PDF 문서 분석 및 추출", tag: "기술", img: "assets/lectures/15강_PDF문서뽀개기_20230831/slide1.png", desc: "스마트한 문서 관리 비법" , totalSlides: 42 },
        { id: "15차시_글로벌_디지털_경제", title: "15차시 글로벌 디지털 경제", tag: "경제", img: "assets/lectures/15차시_글로벌_디지털_경제/slide1.png", desc: "세계 경제 지형과 디지털 혁신" , totalSlides: 60 },
        { id: "16강_비즈니스_이메일_홍보기획서_작성하기_20230831", title: "16강 비즈니스 이메일 홍보 기획", tag: "마케팅", img: "assets/lectures/16강_비즈니스_이메일_홍보기획서_작성하기_20230831/slide1.png", desc: "카피라이팅과 메일 마케팅" , totalSlides: 52 },
        { id: "16차시_4차산업혁명과_리더십", title: "16차시 4차산업혁명과 리더십", tag: "리더십", img: "assets/lectures/16차시_4차산업혁명과_리더십/slide1.png", desc: "혁신 시대의 리더가 갖춰야 할 역량" , totalSlides: 54 },
        { id: "17강_티이핑으로_이미지를_생성하다_20230831", title: "17강 타이핑으로 이미지 생성 실무", tag: "디자인", img: "assets/lectures/17강_티이핑으로_이미지를_생성하다_20230831/slide1.png", desc: "생성형 AI를 활용한 비주얼 기획" , totalSlides: 43 },
        { id: "17차시_로보틱_프로세스_자동화RPA", title: "17차시 로보틱 프로세스 자동화", tag: "기술", img: "assets/lectures/17차시_로보틱_프로세스_자동화RPA/slide1.png", desc: "반복 업무의 AI 자동화" , totalSlides: 48 },
        { id: "18강_AI로_유튜브_동영상_Generator_20230831", title: "18강 AI 동영상 유튜브 리드 생성", tag: "미디어", img: "assets/lectures/18강_AI로_유튜브_동영상_Generator_20230831/slide1.png", desc: "유튜브 마케팅의 AI 적용" , totalSlides: 49 },
        { id: "18차시__5G와_미래_통신_기술", title: "18차시 5G와 미래 통신 기술", tag: "기술", img: "assets/lectures/18차시__5G와_미래_통신_기술/slide1.png", desc: "초고속 인프라의 발전 방향" , totalSlides: 51 },
        { id: "19강_AI로_유튜브_만들기_20230831", title: "19강 AI 활용 유튜브 만들기", tag: "미디어", img: "assets/lectures/19강_AI로_유튜브_만들기_20230831/slide1.png", desc: "콘텐츠 크리에이터를 위한 AI" , totalSlides: 25 },
        { id: "19차시__퀀텀트레이딩", title: "19차시 퀀텀 트레이딩 분석", tag: "금융", img: "assets/lectures/19차시__퀀텀트레이딩/slide1.png", desc: "데이터 금융과 인공지능" , totalSlides: 61 },
        { id: "1강_ChatGPT_EI_02230818", title: "1강 ChatGPT 기초 핵심", tag: "입문", img: "assets/lectures/1강_ChatGPT_EI_02230818/slide1.png", desc: "AI와 대화하는 법 기초" , totalSlides: 37 },
        { id: "1차시_빅데이터의_중요성과_활용사례_20230915", title: "1차시 빅데이터 중요성 및 사례", tag: "데이터", img: "assets/lectures/1차시_빅데이터의_중요성과_활용사례_20230915/slide1.png", desc: "데이터가 만드는 새로운 가치" , totalSlides: 45 },
        { id: "20강_ChatGPT_플러그인1_20230831", title: "20강 ChatGPT 플러그인 1", tag: "기술", img: "assets/lectures/20강_ChatGPT_플러그인1_20230831/slide1.png", desc: "확장 기능을 통한 성능 극대화" , totalSlides: 36 },
        { id: "20차시__바이오인포메틱스", title: "20차시 바이오인포메틱스", tag: "바이오", img: "assets/lectures/20차시__바이오인포메틱스/slide1.png", desc: "생명과학의 디지털 전환" , totalSlides: 51 },
        { id: "21강_ChatGPT_플러그인2_20230831", title: "21강 ChatGPT 플러그인 2", tag: "기술", img: "assets/lectures/21강_ChatGPT_플러그인2_20230831/slide1.png", desc: "실무 연동 및 생산성 강화" , totalSlides: 41 },
        { id: "21차시_인간과_기계의_협업", title: "21차시 인간과 기계의 협업", tag: "미래기술", img: "assets/lectures/21차시_인간과_기계의_협업/slide1.png", desc: "AI 공존 시대의 생존 전략" , totalSlides: 51 },
        { id: "22강_ChatGPT_플러그인3_20230831", title: "22강 ChatGPT 플러그인 3", tag: "기술", img: "assets/lectures/22강_ChatGPT_플러그인3_20230831/slide1.png", desc: "고급 데이터 분석 기능 활용" , totalSlides: 42 },
        { id: "22차시_게임과_게임이론", title: "22차시 게임과 게임이론", tag: "전략", img: "assets/lectures/22차시_게임과_게임이론/slide1.png", desc: "비즈니스 전략과 게임의 활용" , totalSlides: 45 },
        { id: "23강_ChatGPT_플러그인4_20230831", title: "23강 ChatGPT 플러그인 4", tag: "기술", img: "assets/lectures/23강_ChatGPT_플러그인4_20230831/slide1.png", desc: "최종 마스터 가이드" , totalSlides: 54 },
        { id: "23차시_디지털_마케팅", title: "23차시 디지털 마케팅 전략", tag: "마케팅", img: "assets/lectures/23차시_디지털_마케팅/slide1.png", desc: "소비자 니즈 분석과 대응" , totalSlides: 48 },
        { id: "24강_ChatGPT_Codeinterpreter_20230831", title: "24강 ChatGPT Code Interpreter", tag: "데이터", img: "assets/lectures/24강_ChatGPT_Codeinterpreter_20230831/slide1.png", desc: "데이터 분석 자동화 기초" , totalSlides: 50 },
        { id: "24차시_미래_모빌리티_산업의_현황과_도전", title: "24차시 미래 모빌리티 산업", tag: "산업", img: "assets/lectures/24차시_미래_모빌리티_산업의_현황과_도전/slide1.png", desc: "이동 수단의 지능형 변화" , totalSlides: 42 },
        { id: "25강_프리젠테이션을_탈옥하다_20230831", title: "25강 프리젠테이션 자동화 기술", tag: "기획", img: "assets/lectures/25강_프리젠테이션을_탈옥하다_20230831/slide1.png", desc: "AI로 만드는 10초 슬라이드" , totalSlides: 47 },
        { id: "25차시_AI레볼루션과_부의_미래", title: "25차시 AI 레볼루션과 부의 미래", tag: "경제", img: "assets/lectures/25차시_AI레볼루션과_부의_미래/slide1.png", desc: "부의 거대한 이동 분석" , totalSlides: 41 },
        { id: "2강_ChatGPT_EI_20230818", title: "2강 ChatGPT 심화 프롬프팅", tag: "중급", img: "assets/lectures/2강_ChatGPT_EI_20230818/slide1.png", desc: "원하는 답변을 얻는 필살기" , totalSlides: 40 },
        { id: "2차시_로봇공학기초와_자동화_시스템", title: "2차시 로봇공학 기초와 자동화", tag: "기술", img: "assets/lectures/2차시_로봇공학기초와_자동화_시스템/slide1.png", desc: "로봇 기술의 현재와 미래" , totalSlides: 45 },
        { id: "3강_GAI비교_EI_20230819", title: "3강 GAI 비교 분석 입문", tag: "기술", img: "assets/lectures/3강_GAI비교_EI_20230819/slide1.png", desc: "도구별 특징 한눈에 보기" , totalSlides: 24 },
        { id: "3차시_클라우드_컴퓨팅", title: "3차시 클라우드 컴퓨팅 핵심", tag: "기술", img: "assets/lectures/3차시_클라우드_컴퓨팅/slide1.png", desc: "인프라 기술의 기초 이해" , totalSlides: 54 },
        { id: "4강_대화의_기술_레벨1_20230819", title: "4강 대화의 기술 레벨 1", tag: "입문", img: "assets/lectures/4강_대화의_기술_레벨1_20230819/slide1.png", desc: "AI 대화의 첫걸음 강의" , totalSlides: 35 },
        { id: "4차시_IOT_사물인터넷과_산업트렌드", title: "4차시 IoT 사물인터넷 트렌드", tag: "기술", img: "assets/lectures/4차시_IOT_사물인터넷과_산업트렌드/slide1.png", desc: "모든 것이 연결되는 시대" , totalSlides: 57 },
        { id: "5강_활용법프롬프팅5단계_20230819", title: "5강 활용법 프롬프팅 5단계", tag: "실무", img: "assets/lectures/5강_활용법프롬프팅5단계_20230819/slide1.png", desc: "업무 최적화 프로세스 교육" , totalSlides: 24 },
        { id: "5차시_가상현실과_증강현실은_어디로", title: "5차시 가상현실과 증강현실", tag: "미래기술", img: "assets/lectures/5차시_가상현실과_증강현실은_어디로/slide1.png", desc: "몰입형 기술의 발전 분석" , totalSlides: 57 },
        { id: "6차시_블록체인과_금융기술", title: "6차시 블록체인과 금융기술", tag: "금융", img: "assets/lectures/6차시_블록체인과_금융기술/slide1.png", desc: "가상 자산과 보안의 이해" , totalSlides: 53 },
        { id: "7강_GAI와_비즈니스프레임워크_20230819", title: "7강 GAI와 비즈니스프레임워크", tag: "비즈니스", img: "assets/lectures/7강_GAI와_비즈니스프레임워크_20230819/slide1.png", desc: "전략적 사고를 돕는 AI" , totalSlides: 16 },
        { id: "7차시_사이버보안의_중요성과_대응전략_-_복사본", title: "7차시 사이버보안 중요성 및 전략", tag: "기술", img: "assets/lectures/7차시_사이버보안의_중요성과_대응전략_-_복사본/slide1.png", desc: "디지털 자산 방어 교육" , totalSlides: 47 },
        { id: "8강_사무실무과정_20230819", title: "8강 사무실무과정 마스터", tag: "실무", img: "assets/lectures/8강_사무실무과정_20230819/slide1.png", desc: "오피스 생산성의 결실" , totalSlides: 18 },
        { id: "8차시_3D_프린팅과_제조혁신", title: "8차시 3D 프린팅과 제조혁신", tag: "기술", img: "assets/lectures/8차시_3D_프린팅과_제조혁신/slide1.png", desc: "맞춤형 제조의 시대" , totalSlides: 52 },
        { id: "9강__문서양식에_날개_달기_비즈니스_프레임워크_20230819", title: "9강 문서양식에 날개 달기", tag: "기획", img: "assets/lectures/9강__문서양식에_날개_달기_비즈니스_프레임워크_20230819/slide1.png", desc: "보고서의 질을 높이는 비기" , totalSlides: 47 },
        { id: "9차시_디지털_헬스케어의_현황과_미래", title: "9차시 디지털 헬스케어 현황", tag: "미래기술", img: "assets/lectures/9차시_디지털_헬스케어의_현황과_미래/slide1.png", desc: "건강 시스템의 변화 예측" , totalSlides: 59 },
        { id: "ChatGPT_for_Election", title: "ChatGPT for Election", tag: "공공", img: "assets/lectures/ChatGPT_for_Election/slide1.png", desc: "선거 전략을 위한 AI 분석" , totalSlides: 67 },
        { id: "ChatGPT_강의안_부산광역시동구청_0918", title: "ChatGPT 강의안_부산동구청 1", tag: "공공", img: "assets/lectures/ChatGPT_강의안_부산광역시동구청_0918/slide1.png", desc: "행정 업무 혁신 특강" , totalSlides: 254 },
        { id: "ChatGPT_강의안_부산광역시동구청_0925", title: "ChatGPT 강의안_부산동구청 2", tag: "공공", img: "assets/lectures/ChatGPT_강의안_부산광역시동구청_0925/slide1.png", desc: "실무 연동 심화 실습" , totalSlides: 252 },
        { id: "ChatGPT_강의안_부산광역시동구청_1004", title: "ChatGPT 강의안_부산동구청 3", tag: "공공", img: "assets/lectures/ChatGPT_강의안_부산광역시동구청_1004/slide1.png", desc: "최종 결과물 제작 세션" , totalSlides: 251 },
        { id: "ChatGPT_부산동구영성인력개발센터_20230405", title: "ChatGPT 부산동구 여성인력센터", tag: "교육", img: "assets/lectures/ChatGPT_부산동구영성인력개발센터_20230405/slide1.png", desc: "여성 인재를 위한 AI 리터러시" , totalSlides: 196 },
        { id: "ChatGPT_선거전략_20230424", title: "ChatGPT 선거전략 분석", tag: "기획", img: "assets/lectures/ChatGPT_선거전략_20230424/slide1.png", desc: "데이터 기반 선거 캠페인" , totalSlides: 65 },
        { id: "ChatGPT_에센셜_아산에스엔테크_1205_1204", title: "ChatGPT 에센셜 아산에스엔테크", tag: "기업특강", img: "assets/lectures/ChatGPT_에센셜_아산에스엔테크_1205_1204/slide1.png", desc: "조직 핵심 역량 강화 교육" , totalSlides: 260 },
        { id: "ChatGPT_전문면접관특강_20230520", title: "ChatGPT 전문면접관 특강", tag: "인사", img: "assets/lectures/ChatGPT_전문면접관특강_20230520/slide1.png", desc: "선발과 평가의 과학적 도구" , totalSlides: 60 },
        { id: "ChatGPT_중급과정_20230312", title: "ChatGPT 중급과정 패키지", tag: "중급", img: "assets/lectures/ChatGPT_중급과정_20230312/slide1.png", desc: "프로들의 AI 활용법 실전" , totalSlides: 75 },
        { id: "ChatGPT_청년교육_20230526", title: "ChatGPT 청년 교육", tag: "청년", img: "assets/lectures/ChatGPT_청년교육_20230526/slide1.png", desc: "청년 취업과 커리어 설계 AI" , totalSlides: 210 },
        { id: "ChatGPT_크리에이터_강좌_20230423", title: "ChatGPT 크리에이터 강좌", tag: "크리에이티브", img: "assets/lectures/ChatGPT_크리에이터_강좌_20230423/slide1.png", desc: "창작자를 위한 프롬프트 비책" , totalSlides: 117 },
        { id: "ChatGPT_필수과정_20230319", title: "ChatGPT 필수 과정 전용", tag: "입문", img: "assets/lectures/ChatGPT_필수과정_20230319/slide1.png", desc: "반드시 알아야 할 입문 지식" , totalSlides: 82 },
        { id: "ChatGPT_활용기초_20230228", title: "ChatGPT 활용 기초", tag: "입문", img: "assets/lectures/ChatGPT_활용기초_20230228/slide1.png", desc: "가장 쉬운 시작을 위해" , totalSlides: 104 },
        { id: "My_Life_동의대청년멘토링_20230622", title: "My Life 동의대 청년 멘토링", tag: "멘토링", img: "assets/lectures/My_Life_동의대청년멘토링_20230622/slide1.png", desc: "인생 계획과 성장의 러닝메이트" , totalSlides: 14 },
        { id: "메타버스_AGI시대의_나의직업_20230609", title: "메타버스 및 AGI 시대 나의 직업", tag: "미래", img: "assets/lectures/메타버스_AGI시대의_나의직업_20230609/slide1.png", desc: "커리어의 확장과 대응 전략" , totalSlides: 101 },
        { id: "울산저널i-AI동영상제작_특강_1107", title: "울산저널 AI 동영상 특강", tag: "미디어", img: "assets/lectures/울산저널i-AI동영상제작_특강_1107/slide1.png", desc: "언론인 맞춤형 영상 제작 실습" , totalSlides: 15 },
        { id: "울산주력산업_1110", title: "울산 주력산업 분석 및 특강", tag: "산업", img: "assets/lectures/울산주력산업_1110/slide1.png", desc: "지역 산업의 미래 보고서" , totalSlides: 66 },
        { id: "취업역량강화특강_이력서_자기소개서_직무기술서_면접_1017", title: "취업역량강화 특강 통합", tag: "교육", img: "assets/lectures/취업역량강화특강_이력서_자기소개서_직무기술서_면접_1017/slide1.png", desc: "자소서와 면접을 잇는 필승 전략" , totalSlides: 35 }
    ],
    "2024": [
        { id: "1회차_GAI를_활용한_마케팅_20240705_GWPacific강좌", title: "GAI 활용 마케팅 1회차", tag: "마케팅", img: "assets/lectures/1회차_GAI를_활용한_마케팅_20240705_GWPacific강좌/slide1.png", desc: "AI 마케팅의 정석 개요" , totalSlides: 203 },
        { id: "2회차_GAI를_활용한_마케팅_20240705_GWPacific강좌", title: "GAI 활용 마케팅 2회차", tag: "마케팅", img: "assets/lectures/2회차_GAI를_활용한_마케팅_20240705_GWPacific강좌/slide1.png", desc: "실전 데이터 분석 마케팅" , totalSlides: 180 },
        { id: "3회차_생성형_AI를_활용한_이미지_동영상_생성_글로벌코리아_0723", title: "GAI 이미지 동영상 생성 3회차", tag: "크리에이티브", img: "assets/lectures/3회차_생성형_AI를_활용한_이미지_동영상_생성_글로벌코리아_0723/slide1.png", desc: "비주얼 스토리텔링의 한계" , totalSlides: 126 },
        { id: "4회차-GPTs_글로벌코리아_0730", title: "GPTs 맞춤형 챗봇 구축 실무", tag: "기술", img: "assets/lectures/4회차-GPTs_글로벌코리아_0730/slide1.png", desc: "조직만의 AI 전문가 만들기" , totalSlides: 69 },
        { id: "6강_아이디어_20230819", title: "6강 아이디어 혁신 발상법", tag: "기획", img: "assets/lectures/6강_아이디어_20230819/slide1.png", desc: "막힌 생각을 뚫어주는 브레인" , totalSlides: 49 },
        { id: "ChatGPT_for_Election_President_Roh", title: "ChatGPT for Election Pres. Roh", tag: "기획", img: "assets/lectures/ChatGPT_for_Election_President_Roh/slide1.png", desc: "전략 수립을 위한 데이터 분석" , totalSlides: 134 },
        { id: "ChatGPT-4_영어회화법", title: "ChatGPT-4 영어회화 교육법", tag: "교육", img: "assets/lectures/ChatGPT-4_영어회화법/slide1.png", desc: "말하기와 듣기의 동시 완성" , totalSlides: 9 },
        { id: "ChatGPT-vs-Claude-3_0324", title: "ChatGPT vs Claude 3 비교", tag: "기술", img: "assets/lectures/ChatGPT-vs-Claude-3_0324/slide1.png", desc: "글로벌 모델별 강점 분석" , totalSlides: 23 },
        { id: "ChatGPT_청소년_0115", title: "ChatGPT 청소년 교육", tag: "청소년", img: "assets/lectures/ChatGPT_청소년_0115/slide1.png", desc: "디지털 네이티브를 위한 가이드" , totalSlides: 132 },
        { id: "ESG_02", title: "ESG 경영과 AI의 공존", tag: "ESG", img: "assets/lectures/ESG_02/slide1.png", desc: "지속가능을 위한 디지털 전략" , totalSlides: 30 },
        { id: "경북대환경대학원_특강_1107", title: "경북대 환경대학원 초청 특강", tag: "연구", img: "assets/lectures/경북대환경대학원_특강_1107/slide1.png", desc: "학문 탐구를 뒷받침하는 기술" , totalSlides: 127 },
        { id: "공익활동지원센터_20240305", title: "공익활동지원센터 특강 시리즈", tag: "공공", img: "assets/lectures/공익활동지원센터_20240305/slide1.png", desc: "사회적 협력과 소통의 기술" , totalSlides: 41 },
        { id: "국가교육위원회_발표_정우진_20240307", title: "국가교육위원회 정책 발표안", tag: "정부정책", img: "assets/lectures/국가교육위원회_발표_정우진_20240307/slide1.png", desc: "미래 교육 제언 및 실무" , totalSlides: 79 },
        { id: "대구리더스특강_20244025", title: "대구 리더스 특별 특강", tag: "리더십", img: "assets/lectures/대구리더스특강_20244025/slide1.png", desc: "혁신의 리더십 마인드셋" , totalSlides: 68 },
        { id: "대현초특강_0926", title: "대현초등학교 학생 AI 특강", tag: "교육", img: "assets/lectures/대현초특강_0926/slide1.png", desc: "질의 응답으로 배우는 코딩" , totalSlides: 26 },
        { id: "동구노동자센터", title: "동구 노동자지원센터 실습", tag: "복지", img: "assets/lectures/동구노동자센터/slide1.png", desc: "생활 밀착형 도구 사용법" , totalSlides: 114 },
        { id: "동구노동자센터_특강_0926", title: "동구 노동자지원센터 특강 0926", tag: "복지", img: "assets/lectures/동구노동자센터_특강_0926/slide1.png", desc: "업무 생산성 향상의 비결" , totalSlides: 229 },
        { id: "동구노동자센터_특강_1029", title: "동구 노동자지원센터 특강 1029", tag: "복지", img: "assets/lectures/동구노동자센터_특강_1029/slide1.png", desc: "더 깊이 있는 AI 활용 실습" , totalSlides: 68 },
        { id: "부여군청_20240509", title: "부여군청 행정 혁신 강의", tag: "공공", img: "assets/lectures/부여군청_20240509/slide1.png", desc: "공공 행정의 효율성 마스터" , totalSlides: 112 },
        { id: "부여군청_20240509_강의버전", title: "부여군청 강의 실전 버전", tag: "공공", img: "assets/lectures/부여군청_20240509_강의버전/slide1.png", desc: "현장 즉시 적용 가능한 팁" , totalSlides: 182 },
        { id: "북구청공무원특강_20240827", title: "북구청 공무원 역량 강화", tag: "공공", img: "assets/lectures/북구청공무원특강_20240827/slide1.png", desc: "스마트 행정 구현의 첫걸음" , totalSlides: 211 },
        { id: "삼산고_특강_1016", title: "삼산고등학교 학생 창의 특강", tag: "청소년", img: "assets/lectures/삼산고_특강_1016/slide1.png", desc: "꿈을 설계하는 생성형 도구" , totalSlides: 234 },
        { id: "서울시_AI정책_1128", title: "서울시 AI 정책 로드맵 제언", tag: "정부정책", img: "assets/lectures/서울시_AI정책_1128/slide1.png", desc: "글로벌 경쟁력 확보의 기틀" , totalSlides: 32 },
        { id: "성남청소년문화의집_1023", title: "성남 청소년 문화의집 교육", tag: "청소년", img: "assets/lectures/성남청소년문화의집_1023/slide1.png", desc: "체험형 데이터 리터러시" , totalSlides: 253 },
        { id: "성남청소년문화의집_2", title: "성남 청소년 문화의집 2", tag: "청소년", img: "assets/lectures/성남청소년문화의집_2/slide1.png", desc: "창의력 폭발 프로젝트 결과" , totalSlides: 20 },
        { id: "성신고_특강_1014", title: "성신고등학교 고등 사고 교육", tag: "교육", img: "assets/lectures/성신고_특강_1014/slide1.png", desc: "비판적 사고와 AI의 협동" , totalSlides: 234 },
        { id: "연암초_1015", title: "연암초등학교 디지털 체험", tag: "교육", img: "assets/lectures/연암초_1015/slide1.png", desc: "아이들이 즐거운 미래 교실" , totalSlides: 89 },
        { id: "영남이공대학교_20240511", title: "영남이공대학교 산학 연계 특강", tag: "교육", img: "assets/lectures/영남이공대학교_20240511/slide1.png", desc: "현장 실무형 인재의 도구" , totalSlides: 68 },
        { id: "오픈이노포럼", title: "오픈 이노베이션 포럼 발제", tag: "비즈니스", img: "assets/lectures/오픈이노포럼/slide1.png", desc: "혁신의 시너지를 만드는 법" , totalSlides: 37 },
        { id: "오픈이노포럼_특강_0925", title: "오픈 이노베이션 특강 0925", tag: "비즈니스", img: "assets/lectures/오픈이노포럼_특강_0925/slide1.png", desc: "실전 네트워크와 데이터" , totalSlides: 60 },
        { id: "울산간호사협회_1126", title: "울산 간호사협회 AI 케어", tag: "의료", img: "assets/lectures/울산간호사협회_1126/slide1.png", desc: "보건 역량 강화를 위한 기술" , totalSlides: 36 },
        { id: "울산과학대_1212", title: "울산 과학대학교 직무 특강", tag: "교육", img: "assets/lectures/울산과학대_1212/slide1.png", desc: "예비 직업인의 AI 기초 기술" , totalSlides: 52 },
        { id: "울산저널_20240514", title: "울산저널 미디어 비즈니스", tag: "미디어", img: "assets/lectures/울산저널_20240514/slide1.png", desc: "언론 시장의 변곡과 대응" , totalSlides: 112 },
        { id: "은월초_특강", title: "은월초등학교 미래 상상력", tag: "교육", img: "assets/lectures/은월초_특강/slide1.png", desc: "무한한 가능성의 디지털 그림" , totalSlides: 89 },
        { id: "인제대_1213", title: "인제대학교 캠퍼스 혁신 교육", tag: "교육", img: "assets/lectures/인제대_1213/slide1.png", desc: "대학 생활의 가치를 높이는 AI" , totalSlides: 59 },
        { id: "인제대특강_20240717", title: "인제대학교 특강 0717", tag: "교육", img: "assets/lectures/인제대특강_20240717/slide1.png", desc: "연구와 학습의 고도화 가이드" , totalSlides: 79 },
        { id: "화봉중_20241220", title: "화봉중학교 청소년 비전 설계", tag: "청소년", img: "assets/lectures/화봉중_20241220/slide1.png", desc: "나를 알아가는 AI 데이터 여행" , totalSlides: 44 }
    ],
    "2025": [
        { id: "AI_활용_관광_데이터_구조화_실습_설계_pptx_3_4회차_V2", title: "AI 관광 데이터 구조화 실무", tag: "기술", img: "assets/lectures/AI_활용_관광_데이터_구조화_실습_설계_pptx_3_4회차_V2/slide1.png", desc: "데이터 사이언스의 관광 도메인 적용" , totalSlides: 70 },
        { id: "AI_춘천_시민_스태프_되다", title: "AI 춘천 시민 스태프 활성화", tag: "시민기획", img: "assets/lectures/AI_춘천_시민_스태프_되다/slide1.png", desc: "시민이 주인이 되는 디지털 거버넌스" , totalSlides: 54 },
        { id: "AI-2025-AI", title: "AI-2025-AI 통합 보고서", tag: "보고서", img: "assets/lectures/AI-2025-AI/slide1.png", desc: "다년간의 데이터가 그려내는 2025" , totalSlides: 68 },
        { id: "AI_정책개발_영상콘티", title: "AI_정책개발 전용 영상 콘티", tag: "미디어", img: "assets/lectures/AI_정책개발_영상콘티/slide1.png", desc: "비전 전달을 위한 시나리오 기획" , totalSlides: 7 },
        { id: "AI_현대_0925", title: "AI_현대 산업 현장 도입 0925", tag: "산업", img: "assets/lectures/AI_현대_0925/slide1.png", desc: "스마트 팩토리의 실제 도입 성과" , totalSlides: 62 },
        { id: "AI강좌", title: "AI강좌 통합 마스터 플랜", tag: "교육", img: "assets/lectures/AI강좌/slide1.png", desc: "체계적인 커리큘럼 아카이브북" , totalSlides: 32 },
        { id: "ai_study_strategy_v1", title: "AI 학습 전략 V1 기본편", tag: "교육", img: "assets/lectures/ai_study_strategy_v1/slide1.png", desc: "학습 효과를 높이는 인지 과학과 AI" , totalSlides: 23 },
        { id: "ai_study_strategy_v2_고헌중", title: "AI 학습 전략 V2 고헌중 센터", tag: "교육", img: "assets/lectures/ai_study_strategy_v2_고헌중/slide1.png", desc: "중학생 맞춤형 심화 학습 도구" , totalSlides: 29 },
        { id: "ai_study_strategy_v2_천곡중", title: "AI 학습 전략 V2 천곡중 센터", tag: "교육", img: "assets/lectures/ai_study_strategy_v2_천곡중/slide1.png", desc: "지역 인재 양성을 위한 특강 자료" , totalSlides: 29 },
        { id: "data_center_toxin_medicine_analysis_2025_건강사회를위한약사회", title: "데이터센터 입지 영향 분석", tag: "연구", img: "assets/lectures/data_center_toxin_medicine_analysis_2025_건강사회를위한약사회/slide1.png", desc: "인프라 건립이 주는 사회적 가치" , totalSlides: 37 },
        { id: "ulsan_datacenter_impact_analysis_V1", title: "울산 데이터센터 임팩트 리서치", tag: "연구", img: "assets/lectures/ulsan_datacenter_impact_analysis_V1/slide1.png", desc: "지역 경제 성장 기여도 정밀 분석" , totalSlides: 20 },
        { id: "경기_수진초등학교_0416", title: "경기 수진초등학교 학생 강좌", tag: "청소년", img: "assets/lectures/경기_수진초등학교_0416/slide1.png", desc: "호기심을 기술로 바꾸는 교육" , totalSlides: 58 },
        { id: "경기_청석초등학교_0424", title: "경기 청석초등학교 학생 강좌", tag: "청소년", img: "assets/lectures/경기_청석초등학교_0424/slide1.png", desc: "나만의 첫 번째 AI 프로젝트" , totalSlides: 64 },
        { id: "공감연대_청년토론회_0220_v1", title: "공감연대 청년 대화", tag: "청년", img: "assets/lectures/공감연대_청년토론회_0220_v1/slide1.png", desc: "청년들의 불안을 희망으로 바꾸는 AI" , totalSlides: 20 },
        { id: "구미사곡초등학교_0926_학생용", title: "구미 사곡초등학교 특강", tag: "청소년", img: "assets/lectures/구미사곡초등학교_0926_학생용/slide1.png", desc: "미래 직업을 미리 가보는 AI 체험" , totalSlides: 86 },
        { id: "데이터센터_건립_울산", title: "데이터센터 건립 관련 정책 제언", tag: "정부정책", img: "assets/lectures/데이터센터_건립_울산/slide1.png", desc: "디지털 자산 축적을 위한 입법 기술" , totalSlides: 38 },
        { id: "도심리빙랩", title: "도심 리빙랩 실천 가이드북", tag: "미래기술", img: "assets/lectures/도심리빙랩/slide1.png", desc: "현장의 소리를 정책에 입히는 기술" , totalSlides: 133 },
        { id: "동지여자고등학교-특강", title: "동지여자고등학교 정기 특강", tag: "교육", img: "assets/lectures/동지여자고등학교-특강/slide1.png", desc: "여고생들을 위한 융합 인재 가이드" , totalSlides: 70 },
        { id: "삼척_원덕중학교_0327_학부형", title: "삼척 원덕중학교 학부형 공유회", tag: "교육", img: "assets/lectures/삼척_원덕중학교_0327_학부형/slide1.png", desc: "자녀 교육을 위한 학부모 AI 문해력" , totalSlides: 75 },
        { id: "삼척_원덕중학교_0327_학생용", title: "삼척 원덕중학교 학생 워크숍", tag: "청소년", img: "assets/lectures/삼척_원덕중학교_0327_학생용/slide1.png", desc: "함께 만들며 배우는 공동체 AI" , totalSlides: 87 },
        { id: "서귀포여고_0325", title: "제주 서귀포여고 명사 초청 특강", tag: "청년", img: "assets/lectures/서귀포여고_0325/slide1.png", desc: "글로벌 시대 제주 인재로 거듭나기" , totalSlides: 75 },
        { id: "성북구의회_0428", title: "성북구의회 의원 특별 세션", tag: "공공", img: "assets/lectures/성북구의회_0428/slide1.png", desc: "의정 혁신과 시민 데이터 활용" , totalSlides: 78 },
        { id: "순창북중학교_0312", title: "순창북중학교 농산어촌 특강", tag: "교육", img: "assets/lectures/순창북중학교_0312/slide1.png", desc: "디지털 격차 없는 균등한 교육" , totalSlides: 275 },
        { id: "정책제안_ppt_정우진_최종본", title: "최종 정책 제안용 슬라이드 덱", tag: "기획", img: "assets/lectures/정책제안_ppt_정우진_최종본/slide1.png", desc: "정우진 전문가의 설득 비결 집약" , totalSlides: 27 },
        { id: "휴먼AI에이전트_양성강좌_02", title: "휴먼 AI 에이전트 양성 강좌 02", tag: "전문가", img: "assets/lectures/휴먼AI에이전트_양성강좌_02/slide1.png", desc: "파트너로서의 AI와 지능형 협업" , totalSlides: 44 },
        { id: "휴먼AI에이전트_양성강좌_v1", title: "휴먼 AI 에이전트 양성 강좌 V1", tag: "전문가", img: "assets/lectures/휴먼AI에이전트_양성강좌_v1/slide1.png", desc: "새로운 직업군의 탄생과 교육" , totalSlides: 45 }
    ],
    "2026": [
        { 
            id: "울산데이터센터_20260422", 
            title: "데이터센터, 문명의 엔진인가! 기후위기의 가속인가!", 
            tags: ["강연", "정우진", "울산데이터센터", "민주노총울산지역본부"], 
            img: "assets/lectures/울산데이터센터_20260422/slide1.png", 
            desc: "2026년 4월 22일 민주노총 울산지역본부에서 진행된 기획 강좌 발표 자료입니다.", 
            totalSlides: 119 
        },
        { 
            id: "강의안_Day_01", 
            title: "강의안 Day 01", 
            tags: ["2026", "AI", "Core"], 
            img: "assets/lectures/강의안_Day_01/slide1.png", 
            desc: "AI의 기초와 핵심 원리를 다루는 2026년 정규 교육 과정의 첫 번째 강의입니다.",
            totalSlides: 60,
            youtubeUrl: "youtube.html"
        },
        { id: "강의안_Day_02", title: "강의안 Day 02 전략 심화", tag: "커리큘럼", img: "assets/lectures/강의안_Day_02/slide1.png", desc: "사례 중심의 비즈니스 딥다이브" , totalSlides: 88 },
        { id: "강의안_Day_03", title: "강의안 Day 03 기술 실습", tag: "커리큘럼", img: "assets/lectures/강의안_Day_03/slide1.png", desc: "직접 짜보고 돌려보는 AI 파이프라인" , totalSlides: 70 },
        { id: "강의안_Day_04", title: "강의안 Day 04 융합 기획", tag: "커리큘럼", img: "assets/lectures/강의안_Day_04/slide1.png", desc: "타 기술과의 연계를 통한 가치 증폭" , totalSlides: 40 },
        { id: "강의안_Day_05", title: "강의안 Day 05 도메인 확장", tag: "커리큘럼", img: "assets/lectures/강의안_Day_05/slide1.png", desc: "현장 문제 해결을 위한 타겟 솔루션" , totalSlides: 40 },
        { id: "강의안_Day_06", title: "강의안 Day 06 최종 평가", tag: "커리큘럼", img: "assets/lectures/강의안_Day_06/slide1.png", desc: "교육의 완성 및 성과물 아카이빙" , totalSlides: 82 },
        { id: "로타리클럽_강의안", title: "로타리클럽 초청 미래 전략 특강", tag: "사회공헌", img: "assets/lectures/로타리클럽_강의안/slide1.png", desc: "공동체 가치를 위한 따뜻한 인공지능" , totalSlides: 61 }
    ]
};
